name: Public API Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  postman-and-sdk-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    services:
      postgres:
        image: timescale/timescaledb:latest-pg14
        env:
          POSTGRES_USER: lotus
          POSTGRES_PASSWORD: lotus
          SSLMODE: PREFER
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: redis
        ports:
          - 6379:6379
        # Set health checks to wait until redis has started
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    environment: Development

    env:
      DJANGO_SETTINGS_MODULE: "lotus.settings"
      PYTHONPATH: "."
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      STRIPE_LIVE_SECRET_KEY: ${{ secrets.STRIPE_LIVE_SECRET_KEY }}
      STRIPE_TEST_SECRET_KEY: ${{ secrets.STRIPE_TEST_SECRET_KEY }}
      DEBUG: False
      KAFKA_URL: "localhost:9092"
      PYTHONDONTWRITEBYTECODE: 1
      SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
      SELF_HOSTED: "${{ secrets.SELF_HOSTED }}"
      POSTMAN_API_KEY: ${{ secrets.postmanApiKey }}

    steps:
      - uses: actions/checkout@v4

      - name: start redpanda
        run: |
          docker run -d --name redpanda \
            -p 9092:9092 \
            docker.redpanda.com/redpandadata/redpanda:v22.2.2 \
            redpanda start --overprovisioned --smp 1 --memory 1G \
            --reserve-memory 0M --node-id 0 --check=false \
            --kafka-addr PLAINTEXT://0.0.0.0:9092 \
            --advertise-kafka-addr PLAINTEXT://localhost:9092

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install poetry
        run: |
          python -m pip install --upgrade poetry wheel

      - id: cache-poetry
        uses: actions/cache@v4
        with:
          path: ~/.cache/pypoetry
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libcairo2-dev postgresql-client

      - name: Install dependencies
        if: steps.cache-poetry.outputs.cache-hit != 'true'
        run: |
          poetry install --no-root

      - name: Create TimescaleDB template database
        run: |
          psql -h localhost -U lotus -c "CREATE DATABASE template_timescale;"
          psql -h localhost -U lotus -d template_timescale -c "CREATE EXTENSION IF NOT EXISTS timescaledb CASCADE;"
          psql -h localhost -U lotus -c "UPDATE pg_database SET datistemplate = true WHERE datname = 'template_timescale';"
          psql -h localhost -U lotus -c "SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname = 'template_timescale' AND pid <> pg_backend_pid();"
          psql -h localhost -U lotus -c "UPDATE pg_database SET datallowconn = false WHERE datname = 'template_timescale';"
        env:
          PGPASSWORD: lotus

      - name: Migrate
        run: |
          poetry run python manage.py migrate --noinput

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Capture Outputs
        run: |
          OUTPUTS=$(poetry run python manage.py postman_ci_outputs)
          KEY=$(echo "$OUTPUTS" | grep "KEY=" | cut -d= -f2)
          PLAN_ID=$(echo "$OUTPUTS" | grep "PLAN_ID=" | cut -d= -f2)
          INVOICE_ID=$(echo "$OUTPUTS" | grep "INVOICE_ID=" | cut -d= -f2)
          ADDON_ID=$(echo "$OUTPUTS" | grep "ADDON_ID=" | cut -d= -f2)
          METRIC_ID=$(echo "$OUTPUTS" | grep "METRIC_ID=" | cut -d= -f2)
          UNUSED_METRIC_ID=$(echo "$OUTPUTS" | grep "UNUSED_MID=" | cut -d= -f2)
          FEATURE_ID=$(echo "$OUTPUTS" | grep "FEATURE_ID=" | cut -d= -f2)
          FEATURE_NAME=$(echo "$OUTPUTS" | grep "FEATURE_NAME=" | cut -d= -f2)
          EVENT_NAME=$(echo "$OUTPUTS" | grep "EVENT_NAME=" | cut -d= -f2)
          CUSTOMER_ID=$(echo "$OUTPUTS" | grep "CUSTOMER_ID=" | cut -d= -f2)
          ENV_JSON=$(jq -n \
            --arg key "$KEY" \
            --arg plan_id "$PLAN_ID" \
            --arg invoice_id "$INVOICE_ID" \
            --arg addon_id "$ADDON_ID" \
            --arg metric_id "$METRIC_ID" \
            --arg feature_name "$FEATURE_NAME" \
            --arg feature_id "$FEATURE_ID" \
            --arg event_name "$EVENT_NAME" \
            --arg customer_id "$CUSTOMER_ID" \
            '{KEY: $key, PLAN_ID: $plan_id, INVOICE_ID: $invoice_id, ADDON_ID: $addon_id, METRIC_ID: $metric_id, FEATURE_NAME: $feature_name, FEATURE_ID: $feature_id,EVENT_NAME: $event_name, CUSTOMER_ID: $customer_id, URL: "http://localhost:8000"}')
          echo "$ENV_JSON" > environment.json
          echo "LOTUS_API_KEY=$KEY" >> $GITHUB_ENV
          echo "PLAN_ID=$PLAN_ID" >> $GITHUB_ENV
          echo "METRIC_ID=$METRIC_ID" >> $GITHUB_ENV
          echo "UNUSED_METRIC_ID=$UNUSED_METRIC_ID" >> $GITHUB_ENV
          echo "FEATURE_ID=$FEATURE_ID" >> $GITHUB_ENV
          echo "ADDON_ID=$ADDON_ID" >> $GITHUB_ENV
          echo "LOTUS_HOST=http://localhost:8000" >> $GITHUB_ENV

      - name: Run server
        run: |
          poetry run python manage.py runserver &

      - name: Run Postman
        if: ${{ env.POSTMAN_API_KEY != '' }}
        id: run-newman
        uses: anthonyvscode/newman-action@v1
        with:
          apiKey: ${{ secrets.postmanApiKey }}
          collection: 18225965-f895719c-ab58-4f3d-ba21-5c918691697e
          environment: environment.json
          reporters: cli

      - name: Output summary to console
        if: ${{ env.POSTMAN_API_KEY != '' }}
        run: echo ${{ steps.run-newman.outputs.summary }}
